_wandb:
    value:
        cli_version: 0.22.0
        e:
            m2nfqsrvj58todqm74zhg9ous0z3e61z:
                codePath: Assignments/Assg1/wandb.ipynb
                codePathLocal: wandb.ipynb
                cpu_count: 10
                cpu_count_logical: 20
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "60708655104"
                email: alicia.mand.aem@gmail.com
                executable: /bin/python3
                git:
                    commit: 6858ef4096cb337e80a9666c72dd18371082c01d
                    remote: https://github.com/physics-png/Phys805.git
                gpu: NVIDIA GeForce RTX 3050 Ti Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
                      uuid: GPU-da81ba83-7b9b-4006-abb4-305f6d9abcdb
                host: Alicia-Dell
                memory:
                    total: "8152854528"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /mnt/c/Users/alici/Documents/GradSchool/Phys805/Assignments/Assg1/wandb.ipynb
                python: CPython 3.10.12
                root: /mnt/c/Users/alici/Documents/GradSchool/Phys805/Assignments/Assg1
                startedAt: "2025-09-22T21:58:04.139282Z"
                writerId: m2nfqsrvj58todqm74zhg9ous0z3e61z
        m: []
        python_version: 3.10.12
        t:
            "3":
                - 2
                - 16
            "4": 3.10.12
            "5": 0.22.0
            "8":
                - 2
                - 1
            "12": 0.22.0
            "13": linux-x86_64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
